### ISSUE TITLE
database download link is not valid

### ISSUE THREAD

**Issue by yehosef** [Sefaria/Sefaria-Export#1]
Also - drop box might not be the greatest option.  It used to be I had to add it to my dropbox account before I downloaded it and it was too big for the free account.  I think a google drive or s3 link might be a better option.

**Comment by edamboritz** [comment]
Hi, the links in the readme are fixed.
The database is no longer served from Dropbox. 

Thank you for pointing this out!

**Comment by yehosef** [comment]
Thanks for the update - I can download the file but it seems it's broken (at least for me on OSX).  I downloaded the smaller version and tried to unzip - here's what happened:

https://www.evernote.com/l/ADAubm0uhMpK9q17pHtStAyipcGc-u_hygs
(sorry - had a problem with the github upload..)

**Comment by edamboritz** [comment]
Hi, I have tried the link again and it downloads and extracts fine for me. 
I'd advise deleting anything previously downloaded and trying again with a fresh download

**Comment by yehosef** [comment]
I had tried a few (5+) times and it didn't work.  It was ending the transfer early.  Seems it might have been a problem with my internet connection and/or the way the sefaria servers were serving the files.  I got it to work using Firefox DownloadThemAll.  Thanks!
