### ISSUE TITLE
Can you clarify the licenses of this content?

### ISSUE THREAD

**Issue by citelao** [Sefaria/Sefaria-Export#16]
This is very cool content! Your README states:

> Structured Jewish texts and metadata with free public licenses, exported from Sefaria's database.

Can you clarify what those licenses are? I imagine that different licenses affect how people can use this information.

Thanks!

**Comment by blockspeiser** [comment]
Inside the JSON versions of each of the text you'll see a "license" field. Generally this will be either "Public Domain", "CC0", "CC-BY", "CC-BY-SA" or "CC-BY-NC".

You can see details for each of the Creative Commons licenses here: https://creativecommons.org/licenses/

Thanks
