### ISSUE TITLE
Siddur License

### ISSUE THREAD

**Issue by ShulertApp** [Sefaria/Sefaria-Export#18]
Hi! We are curious whether we can use your siddur commercially. What is the license?

**Comment by nsantacruz** [comment]
This depends on the exact version(s) you want to use. To find the license for a version on Sefaria
1) Open the book you are interested in
2) Find the version you are interested in in the "Translations" button in the sidebar
3) The license should be listed on the version in this list. If the license is a Creative Commons license, you can click on the link to learn more about the license

Tell me if you have any questions

**Comment by ShulertApp** [comment]
Thanks!
