### ISSUE TITLE
Smaller data dump is corrupted

### ISSUE THREAD

**Issue by nassan** [Sefaria/Sefaria-Export#2]
I have tried multiple times to download the data without text history and I cannot extract the tarball. Unexpected EOF. Please verify that file is healthy.

**Comment by nsantacruz** [comment]
I don't believe it's corrupted. Because the file is large, the download sometimes stops in the middle. To ensure you get the whole file, download it from the command line using `wget -c URL`. This is assuming you're on Linux or Mac. Not sure if there's a simple way to do this on Windows.

**Comment by nsantacruz** [comment]
The file is verified to be uncorrupted. This error generally happens because the download is very large and the server drops the connection in the middle. The best way to download it is through the command line on your computer using `wget -c`
