### ISSUE TITLE
Versions of the Talmud

### ISSUE THREAD

**Issue by erelsgl** [Sefaria/Sefaria-Export#3]
I am doing some research on Talmud text, using the excellent edition of William Davidson. I have several questions:

* What is the "merged" version?
* Some tractates have no William Davidson edition; are you planning to add these tractates in the near future?

Thanks!!!

**Comment by rneiss** [comment]
Hi,

1. The repos readme file describes the merged version fairly well:

> Each terminal directory also includes a file called merged (e.g., merged.json or merged.txt). This file uses the same logic used on the Sefaria web site to include the maximal content available. For example, we have cases in the Mishnah where no single English version is complete by itself, but the merged version will include a complete text that picks and merges from multiple sources as needed.

>When we do have complete versions of texts, we will still include a merged file. In that case, the merged file will be a copy of the default complete version. This simplifies many applications - you are always guarenetted that by looking at the merged version you'll see a maximal amount of text available, with preference for the text versions we've set.

2. We will continue to add translations to the William Davidson Talmud as they become available via our partnership with Koren Publishers (https://blog.sefaria.org/2017/02/07/setting-the-talmud-free/).
