### ISSUE TITLE
Download does not include vocalised text for tractate Peshachim in Talmud Bavli

### ISSUE THREAD

**Issue by JamesRead5737** [Sefaria/Sefaria-Export#32]
On the sefaria website I am able to access vocalised text for the Pesachim tractate of the Talmud Bavli but the download doesn't seem to include it. On closer inspection I noticed that this is the case for a number of tractates. Are there any plans to update and include the vocalised versions?

**Comment by nsantacruz** [comment]
Unfortunately, we only update the export in this repo about once a year. Likely this text didn't make it into the last update. You can download the text from our site here: https://www.sefaria.org/Pesachim
